package se.yrgo.dataaccess;

import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

import se.yrgo.domain.Action;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

import java.sql.JDBCType;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String DELETE_SQL = "DELETE FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String UPDATE_SQL = "UPDATE CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String INSERT_SQL = "INSERT INTO CUSTOMER (CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?,?,?,?,?)";
    private static final String GET_CUSTOMER_ID_SQL = "SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String GET_NAME_SQL = "SELECT * FROM CUSTOMER WHERE COMPANY_NAME=?";
    private static final String GET_CALLS_SQL = "SELECT * FROM CALLS WHERE CUSTOMER_ID=?";
    private static final String INSERT_CALLS_SQL = "INSERT INTO CALLS (CUSTOMER_ID, TIME_AND_DATE, NOTES) VALUES (?,?,?)";

    private JdbcTemplate template;

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template){
        this.template = template;
        createTables();

    }

    public void createTables(){
        try{
            this.template.update("""
            CREATE TABLE CUSTOMER(
                CUSTOMER_ID VARCHAR(10) PRIMARY KEY NOT NULL,
                COMPANY_NAME VARCHAR(80) NOT NULL,
                EMAIL VARCHAR(60),
                TELEPHONE VARCHAR(60),
                NOTES VARCHAR(100) NOT NULL
            )
            """);

            this.template.update("""
            CREATE TABLE CALLS(
                CALL_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                CUSTOMER_ID VARCHAR(60) NOT NULL,
                TIME_AND_DATE DATE NOT NULL,
                NOTES VARCHAR(100) NOT NULL,
                FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
            )
            """);
        } catch (org.springframework.jdbc.BadSqlGrammarException e){
            System.out.println("Assuming the Customer and Calls tables exist");
        }
    }

    @Override
    public void create(Customer customer) {
        template.update(INSERT_SQL, customer.getCustomerId(), customer.getCompanyName(),customer.getEmail(), customer.getTelephone(), customer.getNotes());
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        List<Customer> customers = template.query(GET_CUSTOMER_ID_SQL, new CustomerRowMapper(), customerId);

        if (customers.isEmpty()) {
            throw new RecordNotFoundException();
        }

        return customers.getFirst();
    }

    @Override
    public List<Customer> getByName(String name) {
        return template.query(GET_NAME_SQL, new CustomerRowMapper(), name);
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        template.update(UPDATE_SQL, customerToUpdate.getCompanyName(), customerToUpdate.getEmail(), customerToUpdate.getTelephone(), customerToUpdate.getNotes(), customerToUpdate.getCustomerId());
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        template.update(DELETE_SQL, oldCustomer.getCustomerId());
    }

    @Override
    public List<Customer> getAllCustomers() {
        return template.query("SELECT * FROM CUSTOMER", new CustomerRowMapper());
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        Customer customer = getById(customerId);

        if (customer == null) {
            throw new RecordNotFoundException();
        }

        List<Call> calls = template.query(GET_CALLS_SQL, new CallRowMapper(), customerId);

        customer.setCalls(calls);

        return customer;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        getById(customerId);

        template.update(INSERT_CALLS_SQL,
                customerId,
                newCall.getTimeAndDate(),
                newCall.getNotes()
        );
    }
}

class CustomerRowMapper implements RowMapper<Customer> {
    public Customer mapRow(ResultSet rs, int arg1) throws SQLException {
        String customerId = rs.getString(1);
        String companyName = rs.getString(2);
        String email = rs.getString(3);
        String telephone = rs.getString(4);
        String notes = rs.getString(5);

        return new Customer(customerId, companyName, email, telephone, notes);
    }

}

class CallRowMapper implements RowMapper<Call> {
    public Call mapRow(ResultSet rs, int arg1) throws SQLException {
        String notes = rs.getString(4);
        Date date = rs.getDate(3);
        Call call = new Call(notes, date);
        return call;
    }
}